version: '3'
services:
  app:
    image: node:19
    ports:
      - "${PORT}:1337"
    links:
      - db
    command: sh -c "npm install && cd client && npm install && npm run build && cd .. && npm start"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - "MONGO_DB=$MONGO_DB"
  db:
    image: mongo
    volumes:
      - ./data/db:/data/db # Creating persistence of database data